const ACTIONS = {
    IS_MOBILE: 'IS_MOBILE',
    // INIT_SESSION: 'INIT_SESSION',
    // LEGAL_STATE_PART: 'LEGAL_STATE_PART',
    // START_DATE: 'START_DATE',
    // END_DATE: 'END_DATE',
    // COUNTER_TYPE: 'COUNTER_TYPE',
    // DIALOG_OPEN: 'DIALOG_OPEN',
    // DIALOG_VALUE: 'DIALOG_VALUE',
    // DIALOG_VALUES_LIST: 'DIALOG_VALUES_LIST',
    // MENU_SIMPLE_CLICK: 'MENU_SIMPLE_CLICK',
    // TABLE_SORT: 'TABLE_SORT',
    // OPEN_ASIDE: 'OPEN_ASIDE',
    // USER_INFO: 'USER_INFO',
    // COUNTERS: 'COUNTERS',
    // COUNTERS_TARIFFS: 'COUNTERS_TARIFFS',
    // COUNTERS_DATA: 'COUNTERS_DATA',
    // TARIFFS_IDS: 'TARIFFS_IDS',
    // USER_ADDRESSES: 'USER_ADDRESSES',
    // COUNTERS_TYPES: 'COUNTERS_TYPES',
    // EXPAND_TREE: 'EXPAND_TREE',
};

export default ACTIONS